import os
# CRITICAL FIX for your system: Redirect Hugging Face downloads to D: drive
# Your C: drive only has 130MB left, which will crash during the 1.5GB model download.
os.environ["HF_HOME"] = "D:/Suvidh/Suvidh/DR.MIGI/models/cache"

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import time

# =======================================================================
# DR. MIGI - Phase 1: The Brain (Tasks 1, 2, 7 & 8)
# =======================================================================

# -----------------------------------------------------------------------
# TASK 1: LLM Architecture (The "Autoregressive Causal Model")
# -----------------------------------------------------------------------
# What it does:
# An LLM like Qwen2.5 is a "Causal Language Model". This means its entire
# architecture is designed to do ONE thing: Predict the next word (token)
# based on all previous words.
# 
# Why it is needed:
# To generate text or reason, the model must understand the sequence of 
# events. "Causal" means it can only look at the past, not the future.
# 
# Architecture Flow (High Level):
# 1. Text -> Tokenizer (converts words to numbers)
# 2. Numbers -> Embeddings (converts numbers to meaning-rich vectors)
# 3. Vectors -> Transformer Blocks (extracts relationships and context)
# 4. Final Output -> Logits (probability distribution over all possible next words)
# -----------------------------------------------------------------------

# -----------------------------------------------------------------------
# TASK 7: Load Qwen Locally (Optimized for Intel i7 CPU)
# -----------------------------------------------------------------------
MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

print(f"Loading Tokenizer from {MODEL_NAME}...")

# -----------------------------------------------------------------------
# TASK 2: Tokenization
# -----------------------------------------------------------------------
# What it does:
# Neural networks only understand numbers, not text. Tokenization breaks 
# down text into smaller subwords (tokens) and maps them to integer IDs.
# 
# How it works internally:
# We use Byte-Pair Encoding (BPE). It groups frequent characters together.
# E.g., "Healthcare" -> might be 1 token. "Unbelievably" -> "Un" + "believably"
#
# Qwen has a vocabulary of ~151,936 tokens. Every integer generated by the
# model corresponds to a specific text segment in this vocabulary.
# -----------------------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print(f"Loading Model {MODEL_NAME} onto CPU...")
# Best Practice: We load the model in `torch.float32` (standard precision).
# While GPUs use float16 to save memory, most CPUs handle float32 better.
# A 0.5B model takes roughly: 0.5 billion params * 4 bytes (float32) = ~2 GB RAM.
# This easily fits into your 16GB system RAM.
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32, 
    device_map="cpu",  # Force execution on the CPU
)
print("Model loaded successfully!")

# -----------------------------------------------------------------------
# TASK 8: Run the first prompt
# -----------------------------------------------------------------------
def run_dr_migi_inference():
    # 1. Define the conversation format
    # Qwen-Instruct expects a specific chat template format (System + User).
    messages = [
        {"role": "system", "content": "You are Dr. MIGI, an AI Healthcare Companion. Be concise and professional."},
        {"role": "user", "content": "Explain briefly what a neural network is."}
    ]

    # 2. Apply Tokenization and Chat Template
    # This formats our Python list into the exact string the model was trained on
    # (e.g., adding <|im_start|> tags) and then converts it to token IDs.
    text_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False, # We get the formatted text first to see what it looks like
        add_generation_prompt=True
    )
    
    print("\n--- FORMATTED PROMPT (What the model actually sees) ---")
    print(text_prompt)

    # 3. Convert formatted text to tensors (multi-dimensional arrays of numbers)
    model_inputs = tokenizer([text_prompt], return_tensors="pt").to("cpu")

    print("\n--- TOKEN IDs ---")
    print(model_inputs.input_ids) # Look at these integers!
    
    print("\nGenerating response... (This may take a moment on CPU)")
    start_time = time.time()

    # 4. Generate the response
    # The model autoregressively generates one token at a time until it hits
    # a special "Stop Token" (e.g., <|im_end|>).
    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=100,      # Don't generate endlessly
        temperature=0.7,         # Controls randomness (lower = more deterministic)
        do_sample=True,          # Enable sampling (allows temperature to work)
        pad_token_id=tokenizer.eos_token_id # Avoids warnings
    )
    
    end_time = time.time()

    # 5. Decode the output
    # We slice out the input tokens from the generated_ids to only print the new text.
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]
    
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    print("\n--- DR. MIGI'S RESPONSE ---")
    print(response)
    print(f"\nTime taken: {end_time - start_time:.2f} seconds")

if __name__ == "__main__":
    run_dr_migi_inference()
